routes/web.php
<?php

use App\Http\Controllers\PageController;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
Auth::routes(['register' => false]);
Route::get('/', ['as' => 'home', 'uses' => '\App\Http\Controllers\PageController@index']);
Route::get('/{slug}', ['as' => 'detail', 'uses' => '\App\Http\Controllers\PageController@single']);
Route::get('/tag/{id}', ['as' => 'tag', 'uses' => '\App\Http\Controllers\PageController@articlesbyTag']);



Route::group(['prefix' => 'admin'], function () {
    Route::resource('tags', '\App\Http\Controllers\Admin\TagController');
    Route::resource('articles', '\App\Http\Controllers\Admin\ArticleController');
    Route::delete('/articles/photo/{id}', ['as' => 'articles.photo-destroy', 'uses' => '\App\Http\Controllers\Admin\ArticleController@destroyPhoto']);
});

app/Models/Article.php
<?php

namespace App\Models;

use App\Models\Model;
use App\Helpers\SlugHelper;

class Article extends Model {

    public function tags() {
        return $this->belongsToMany('App\Models\Tag', 'article_tags');
    }

    public function photos() {
        return $this->hasMany('App\Models\ArticlePhoto');
    }

    public function saveArticle($request, $currentUser = null) {
        $this->setData($request, $currentUser);
        if ($this->save()) {
            $this->attachedRelation($request, 'tags'); //Attached Tags
            return true;
        }
        return false;
    }

    public function updateArticle($request, $currentUser = null) {
        $this->setData($request, $currentUser, true);
        if ($this->update()) {
            $this->syncRelation($request, 'tags'); //Attached Tags
            return true;
        }
        return false;
    }

    private function setData($request, $currentUser, $isEdit = false) {
        $this->creator_id = ($currentUser) ? $currentUser->id : null;
        if ($isEdit) {
            $slug = $this->slug;
            if ($request->input('title') != $this->title) {
                $slug = new SlugHelper($this, $request->input('title'));
                $slug = $slug->getSlug();
            }
        } else {
            $slug = new SlugHelper($this, $request->input('title'));
            $slug = $slug->getSlug();
        }
        $this->slug = $slug;
        $this->title = $request->input('title');
        $this->status = $request->input('status');
        $this->description = $request->input('description');
    }

    public function getPostedOn() {
        return $this->created_at->format('M d, Y') . ' at ' . $this->created_at->format('h:m A');
    }

    public function getFeaturedImage() {
        if ($this->photos->count() > 0) {
            foreach ($this->photos as $photo) {
                if ($photo->is_featured) {
                    return $photo->getImagePath();
                }
            }
        }
        return false;
    }

}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use App\Models\Tag;
use App\Models\Article;
use App\Models\ArticlePhoto;
use App\Http\Requests\ArticleRequest;
use App\Model\Status;

class ArticleController extends Controller {

    private $viewDir;
    private $model;

    public function __construct() {
        $this->viewDir = self::ADMIN_DIR . 'articles.';
    }

    public function index() {
        $models = Article::with(['tags'])->orderBy('id', 'DESC')->get();
        return view($this->viewDir . 'index')->with(compact('models'));
    }

    public function create(Article $article) {
        $model = $article;
        $tags = Tag::where(['status' => Status::STATUS_ACTIVE])->pluck('name', 'id');
        return view($this->viewDir . 'create')->with(compact('model', 'tags'));
    }

    public function store(ArticleRequest $request) {

        if (!$request->ajax()) {
            return response(['Good' => false, 'Message' => 'Invalid request.']);
        }
        $currentUser = Auth::user();
        $this->model = new Article();
        if ($this->model->saveArticle($request, $currentUser)) {
            $isPhotoSaved = ArticlePhoto::insert($this->doUpload($request->photos, ($this->model) ? $this->model->id : null));
            if (!$isPhotoSaved) {
                return response(['Good' => false, 'is_new' => true, 'Message' => 'Article created successfully. But photos not saved.']);
            }
            return response(['Good' => true, 'is_new' => true, 'Message' => 'Article created successfully.']);
        }
        return response(['Good' => false, 'is_new' => true, 'Message' => 'Article not created.']);
    }

    public function show(Article $article) {
        $model = $article->with('tags', 'photos')->find($article->id);
        return view($this->viewDir . 'show')->with(compact('model'));
    }

    public function edit(Article $article) {
        $model = $article->with('tags', 'photos')->find($article->id);
        $tags = Tag::where(['status' => Status::STATUS_ACTIVE])->pluck('name', 'id');
        return view($this->viewDir . 'edit')->with(compact('model', 'tags'));
    }

    public function update(ArticleRequest $request, Article $article) {
        if (!$request->ajax()) {
            return response(['Good' => false, 'Message' => 'Invalid request.']);
        }
        $currentUser = Auth::user();
        $this->model = $article;
        if ($this->model->updateArticle($request, $currentUser)) {
            $isPhotoSaved = ArticlePhoto::insert($this->doUpload($request->photos, ($this->model) ? $this->model->id : null));
            if (!$isPhotoSaved) {
                return response(['Good' => false, 'is_new' => true, 'Message' => 'Article created successfully. But photos not saved.']);
            }
            return response(['Good' => true, 'is_new' => false, 'Message' => 'Article updated successfully.']);
        }
        return response(['Good' => false, 'is_new' => false, 'Message' => 'Article not updated.']);
    }

    public function destroy(Request $request, Article $article) {
        if (!$request->ajax()) {
            return response(['Good' => false, 'Message' => 'Invalid request.']);
        }
        $article->delete();
        return response(['Good' => true, 'Message' => 'Article deleted successfully.']);
    }

    public function destroyPhoto(Request $request, $id) {
        if (!$request->ajax()) {
            return response(['Good' => false, 'Message' => 'Invalid request.']);
        }
        $photo = ArticlePhoto::find($id);
        $photo->delete();
        return response(['Good' => true, 'Message' => 'Photo deleted successfully.']);
    }

    private function doUpload($photos, $articleId) {
        $files = [];
        if (empty($photos)) {
            return $files;
        }

        foreach ($photos as $index => $file) {
            try {
                $destinationPath = public_path(ArticlePhoto::UPLOAD_DIR);
                $fileName = str_random(25) . '.' . $file->getClientOriginalExtension();
                $file->move($destinationPath, $fileName);
                $files[] = ['name' => $fileName, 'article_id' => $articleId, 'is_featured' => ($index == 0) ? 1 : 0];
            } catch (Exception $e) {
                return $e->getMessage();
            }
        }
        return $files;
    }

}

resources/views/admin/articles/create.blade.php
@extends('admin.layouts.core')
@section('content')
<div class="container-fluid">

    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            @include('admin.articles.partials._sub-menu')
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <h4>Create New Article</h4>
                <div id="output"></div>
                {!! Form::model($model,["route"=>array('articles.store'),"class"=>"general_form", "method"=>"POST","id"=>"article-form","enctype"=>"multipart/form-data"]) !!} 
                @include('admin.articles.partials._form')
                <div class="form-group">
                    <button type="submit" id="article-submit-btn" class="btn btn-primary">Save</button>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@section('script')
<script>
    $(function () {
//        $('#tags').multiselect({
//            templates: {
//                li: '<li><a href="javascript:void(0);"><label class="pl-2"></label></a></li>'
//            },
//            nonSelectedText: 'Select Tags',
//            numberDisplayed: 6,
//            selectedClass: 'bg-light',
//            buttonClass: 'form-control multiselect',
//            buttonWidth: '20%',
//            includeSelectAllOption : true,
//            onInitialized: function (select, container) {
//                container.find('input').addClass('d-none');
//            }
//
//        });
    });
</script>
@stop
@endsection

resources/views/admin/articles/edit.blade.php
@extends('admin.layouts.core')
@section('content')
<div class="container-fluid">
    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            @include('admin.articles.partials._sub-menu')
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <h4>Edit Article</h4>
                <div id="output"></div>
                @if($model && $model->photos->count()>0)
                <div class="form-group">
                    <div class="row">
                        @foreach($model->photos as $photo)
                        <div class="col-1">
                            <img src="{{ $photo->getImagePath() }}" width="80">
                            <br>
                            {!! Form::model($model,["route"=>array('articles.photo-destroy',$photo->id),"class"=>"general_form inline-block-form", "method"=>"DELETE","id"=>"article-photo-delete-form-".$photo->id]) !!} 
                            <a data-id="{{ $photo->id }}" class="article-photo-delete-btn"><i class="fas fa-trash "></i></a>
                            {!! Form::close() !!}
                        </div>
                        @endforeach
                    </div>
                </div>
                @endif
                {!! Form::model($model,["route"=>array('articles.update',$model->id),"class"=>"general_form", "method"=>"PUT","id"=>"article-form"]) !!} 
                @include('admin.articles.partials._form')
                <div class="form-group">
                    <button type="submit" id="article-submit-btn" class="btn btn-primary">Update</button>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/articles/index.blade.php
@extends('admin.layouts.core')
@section('content')
<div class="container-fluid">
    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            @include('admin.articles.partials._sub-menu')
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <h4>Articles</h4>
                <div id="output"></div>
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Title</th>
                            <th>Tags</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Title</th>
                            <th>Tags</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @if($models->count()>0)
                        @foreach($models as $model)
                        <tr>
                            <td>{{ $model->id }}</td>
                            <td>{{ $model->title }}</td>
                            <td>{{ $model->pluckImplodeAttribute($model->tags) }}</td>
                            <td>{{ Status::getStatus($model->status) }}</td>
                            <td>
                                <a href="{{ route('articles.show', $model->id) }}"><i class="fas fa-eye"></i></a>
                                | 
                                <a href="{{ route('articles.edit', $model->id) }}"><i class="fas fa-pen-square"></i></a>
                                |
                                {!! Form::model($model,["route"=>array('articles.destroy',$model->id),"class"=>"general_form inline-block-form", "method"=>"DELETE","id"=>"article-delete-form-".$model->id]) !!} 
                                <a href="javascript:void(0);" data-id="{{ $model->id }}" class="article-delete-btn"><i class="fas fa-trash"></i></a>
                                    {!! Form::close() !!}
                            </td>
                        </tr>
                        @endforeach
                        @else
                        <tr>
                            <td colspan="3">No record found.</td>
                        </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/articles/show.blade.php
@extends('admin.layouts.core')
@section('content')
<div class="container-fluid">

    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            @include('admin.articles.partials._sub-menu')
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <h4>Show Article</h4>
                <ul>
                    <li>Name: {{ $model->title }}</li>
                    <li>Status: {{ Status::getStatus($model->status) }}</li>
                    <li>Tags: {{ $model->pluckImplodeAttribute($model->tags) }}</li>
                    <li>Description: {{ $model->description }}</li>
                    <li>Created at: {{ $model->getCreatedAt() }}</li>
                    <li>Updated at: {{ $model->getUpdatedAt() }}</li>
                    <li>Photos</li>
                    <li>@if($model && $model->photos->count()>0)
                        <div class="form-group">
                            <div class="row">
                                @foreach($model->photos as $photo)
                                <div class="col-1">
                                    <img src="{{ $photo->getImagePath() }}" width="80">
                                </div>
                                @endforeach
                            </div>
                        </div>
                        @endif</li>
                </ul>
            </div>
        </div>
    </div>
</div>
@endsection