routes/web.php
<?php

use App\Http\Controllers\PageController;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
Auth::routes(['register' => false]);
Route::get('/', ['as' => 'home', 'uses' => '\App\Http\Controllers\PageController@index']);
Route::get('/{slug}', ['as' => 'detail', 'uses' => '\App\Http\Controllers\PageController@single']);
Route::get('/tag/{id}', ['as' => 'tag', 'uses' => '\App\Http\Controllers\PageController@articlesbyTag']);



Route::group(['prefix' => 'admin'], function () {
    Route::resource('tags', '\App\Http\Controllers\Admin\TagController');
    Route::resource('articles', '\App\Http\Controllers\Admin\ArticleController');
    Route::delete('/articles/photo/{id}', ['as' => 'articles.photo-destroy', 'uses' => '\App\Http\Controllers\Admin\ArticleController@destroyPhoto']);
});

app/Models/Tag.php
<?php

namespace App\Models;

use App\Models\Model;

class Tag extends Model {

    public function articles() {
        return $this->belongsToMany('App\Models\Article', 'article_tags');
    }

    public function saveTag($request, $currentUser = null, $isEdit = false) {
        $this->setData($request, $currentUser);
        if ($isEdit) {
            return $this->update();
        }
        return $this->save();
    }

    private function setData($request, $currentUser) {
        $this->creator_id = ($currentUser) ? $currentUser->id : null;
        $this->name = $request->input('name');
        $this->status = $request->input('status');
        $this->description = $request->input('description');
    }

}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use App\Models\Tag;
use App\Http\Requests\TagRequest;

class TagController extends Controller {

    private $viewDir;
    private $model;

    public function __construct() {
        $this->viewDir = self::ADMIN_DIR . 'tags.';
    }

    public function index() {
        $models = Tag::orderBy('id', 'DESC')->get();
        return view($this->viewDir . 'index')->with(compact('models'));
    }

    public function create(Tag $tag) {
        $model = $tag;
        return view($this->viewDir . 'create')->with(compact('model'));
    }

    public function store(TagRequest $request) {
        if (!$request->ajax()) {
            return response(['Good' => false, 'Message' => 'Invalid request.']);
        }
        $currentUser = Auth::user();
        $this->model = new Tag();
        if ($this->model->saveTag($request, $currentUser)) {
            return response(['Good' => true, 'is_new' => true, 'Message' => 'Tag created successfully.']);
        }
        return response(['Good' => false, 'is_new' => true, 'Message' => 'Tag not created.']);
    }

    public function show(Tag $tag) {
        $model = $tag;
        return view($this->viewDir . 'show')->with(compact('model'));
    }

    public function edit(Tag $tag) {
        $model = $tag;
        return view($this->viewDir . 'edit')->with(compact('model'));
    }

    public function update(TagRequest $request, Tag $tag) {
        if (!$request->ajax()) {
            return response(['Good' => false, 'Message' => 'Invalid request.']);
        }
        $currentUser = Auth::user();
        $this->model = $tag;
        if ($this->model->saveTag($request, $currentUser)) {
            return response(['Good' => true, 'is_new' => false, 'Message' => 'Tag updated successfully.']);
        }
        return response(['Good' => false, 'is_new' => false, 'Message' => 'Tag not updated.']);
    }

    public function destroy(Request $request, Tag $tag) {
        if (!$request->ajax()) {
            return response(['Good' => false, 'Message' => 'Invalid request.']);
        }
        $tag->delete();
        return response(['Good' => true, 'Message' => 'Tag deleted successfully.']);
    }

}

resources/views/admin/tags/create.blade.php
@extends('admin.layouts.core')
@section('content')
<div class="container-fluid">

    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            @include('admin.tags.partials._sub-menu')
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <h4>Create New Tag</h4>
                <div id="output"></div>
                {!! Form::model($model,["route"=>array('tags.store'),"class"=>"general_form", "method"=>"POST","id"=>"tag-form"]) !!} 
                @include('admin.tags.partials._form')
                <div class="form-group">
                    <button type="submit" id="tag-submit-btn" class="btn btn-primary">Save</button>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/tags/edit.blade.php
@extends('admin.layouts.core')
@section('content')
<div class="container-fluid">
    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            @include('admin.tags.partials._sub-menu')
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <h4>Edit Tag</h4>
                <div id="output"></div>
                {!! Form::model($model,["route"=>array('tags.update',$model->id),"class"=>"general_form", "method"=>"PUT","id"=>"tag-form"]) !!} 
                @include('admin.tags.partials._form')
                <div class="form-group">
                    <button type="submit" id="tag-submit-btn" class="btn btn-primary">Update</button>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/tags/index.blade.php
@extends('admin.layouts.core')
@section('content')
<div class="container-fluid">
    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            @include('admin.tags.partials._sub-menu')
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <h4>Tags</h4>
                <div id="output"></div>
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @if($models->count()>0)
                        @foreach($models as $model)
                        <tr>
                            <td>{{ $model->id }}</td>
                            <td>{{ $model->name }}</td>
                            <td>{{ Status::getStatus($model->status) }}</td>
                            <td>
                                <a href="{{ route('tags.show', $model->id) }}"><i class="fas fa-eye"></i></a>
                                | 
                                <a href="{{ route('tags.edit', $model->id) }}"><i class="fas fa-pen-square"></i></a>
                                |
                                {!! Form::model($model,["route"=>array('tags.destroy',$model->id),"class"=>"general_form inline-block-form", "method"=>"DELETE","id"=>"tag-delete-form-".$model->id]) !!} 
                                <a data-id="{{ $model->id }}" class="tag-delete-btn"><i class="fas fa-trash "></i></a>
                                {!! Form::close() !!}
                            </td>
                        </tr>
                        @endforeach
                        @else
                        <tr>
                            <td colspan="3">No record found.</td>
                        </tr>
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/tags/show.blade.php
@extends('admin.layouts.core')
@section('content')
<div class="container-fluid">

    <!-- DataTables Example -->
    <div class="card mb-3">
        <div class="card-header">
            @include('admin.tags.partials._sub-menu')
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <h4>Show Tag</h4>
                <ul>
                    <li>Name: {{ $model->name }}</li>
                    <li>Status: {{ Status::getStatus($model->status) }}</li>
                    <li>Description: {{ $model->description }}</li>
                    <li>Created at: {{ $model->getCreatedAt() }}</li>
                    <li>Updated at: {{ $model->getUpdatedAt() }}</li>
                </ul>
            </div>
        </div>
    </div>
</div>
@endsection