routes/web.php
<?php

use App\Http\Controllers\PageController;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
Auth::routes(['register' => false]);
Route::get('/', ['as' => 'home', 'uses' => '\App\Http\Controllers\PageController@index']);
Route::get('/{slug}', ['as' => 'detail', 'uses' => '\App\Http\Controllers\PageController@single']);
Route::get('/tag/{id}', ['as' => 'tag', 'uses' => '\App\Http\Controllers\PageController@articlesbyTag']);



Route::group(['prefix' => 'admin'], function () {
    Route::resource('tags', '\App\Http\Controllers\Admin\TagController');
    Route::resource('articles', '\App\Http\Controllers\Admin\ArticleController');
    Route::delete('/articles/photo/{id}', ['as' => 'articles.photo-destroy', 'uses' => '\App\Http\Controllers\Admin\ArticleController@destroyPhoto']);
});

resources/views/admin/includes/footer.blade.php
<!-- Sticky Footer -->
<footer class="sticky-footer">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright © Your Website 2018</span>
        </div>
    </div>
</footer>

resources/views/admin/includes/header.blade.php
<nav class="navbar navbar-expand navbar-dark bg-dark static-top">

    <a class="navbar-brand mr-1" href="javascript:void(0);">Welcome {{ (Auth::user())?Auth::user()->name:'' }}</a>

    <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
        <i class="fas fa-bars"></i>
    </button>
</nav>

resources/views/admin/includes/menu.blade.php
<!-- Sidebar -->
<ul class="sidebar navbar-nav">
    <li class="nav-item">
        <a class="nav-link" href="{{ route('tags.index') }}">
            <i class="fas fa-fw fa-tags"></i>
            <span>Tags</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ route('articles.index') }}">
            <i class="fas fa-fw fa-tags"></i>
            <span>Articles</span>
        </a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ route('logout') }}"
           onclick="event.preventDefault();
                       document.getElementById('logout-form').submit();">
            {{ __('Logout') }}
        </a>

        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
            @csrf
        </form>
    </li>
</ul>

resources/views/admin/includes/script.blade.php
{!! Html::script('assets/admin/vendor/jquery/jquery.min.js') !!} 
{!! Html::script('assets/admin/vendor/jquery-easing/jquery.easing.min.js') !!} 
{!! Html::script('assets/admin/vendor/datatables/jquery.dataTables.js') !!} 
{!! Html::script('assets/admin/vendor/datatables/dataTables.bootstrap4.js') !!} 
{!! Html::script('assets/admin/js/sb-admin.min.js') !!} 
{!! Html::script('assets/admin/js/demo/datatables-demo.js') !!} 
{!! Html::script('assets/admin/js/demo/datatables-demo.js') !!} 
{!! Html::script('assets/core/uiblocker/js/jquery.blockUI.js') !!} 
{!! Html::script('assets/core/validation/js/jquery.validationEngine-en.js') !!} 
{!! Html::script('assets/core/validation/js/jquery.validationEngine.js') !!} 
{!! Html::script('assets/core/validation/js/jquery.validationEngine.js') !!}
{!! Html::script('assets/core/bootstrap-multiselect/js/bootstrap-multiselect.js') !!}
{!! Html::script('assets/core/js/jquery.form.min.js') !!} 
{!! Html::script('assets/core/js/core.js') !!} 
{!! Html::script('assets/admin/js/script.js?t='.time()) !!} 

resources/views/admin/includes/style.blade.php
{!!Html::style('assets/admin/vendor/bootstrap/css/bootstrap.min.css')!!}
{!!Html::style('assets/admin/vendor/fontawesome-free/css/all.min.css')!!}
{!!Html::style('assets/admin/vendor/datatables/dataTables.bootstrap4.css')!!}
{!!Html::style('assets/admin/css/sb-admin.css')!!}
{!!Html::style('assets/core/validation/css/validationEngine.jquery.css')!!}
{!!Html::style('assets/core/bootstrap-multiselect/css/bootstrap-multiselect.css')!!}